export interface Property {
  id: string;
  title: string;
  price: number;
  currency: "USD" | "RD$";
  operation: "venta" | "alquiler";
  city: string;
  sector: string;
  bedrooms: number;
  bathrooms: number;
  area: number;
  imageUrl: string;
  type: "Apartamento" | "Casa" | "Terreno" | "Edificio";
  isFavorite?: boolean;
}

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Moderno Apartamento en Piantini",
    price: 285000,
    currency: "USD",
    operation: "venta",
    city: "Santo Domingo",
    sector: "Piantini",
    bedrooms: 3,
    bathrooms: 2,
    area: 145,
    imageUrl: "https://picsum.photos/seed/prop1/800/450",
    type: "Apartamento",
    isFavorite: false,
  },
  {
    id: "2",
    title: "Casa Familiar con Jardín en Naco",
    price: 420000,
    currency: "USD",
    operation: "venta",
    city: "Santo Domingo",
    sector: "Naco",
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    imageUrl: "https://picsum.photos/seed/prop2/800/450",
    type: "Casa",
    isFavorite: true,
  },
  {
    id: "3",
    title: "Apartamento Ejecutivo en Evaristo Morales",
    price: 45000,
    currency: "RD$",
    operation: "alquiler",
    city: "Santo Domingo",
    sector: "Evaristo Morales",
    bedrooms: 2,
    bathrooms: 2,
    area: 110,
    imageUrl: "https://picsum.photos/seed/prop3/800/450",
    type: "Apartamento",
    isFavorite: false,
  },
  {
    id: "4",
    title: "Lujosa Villa en Los Cacicazgos",
    price: 680000,
    currency: "USD",
    operation: "venta",
    city: "Santo Domingo",
    sector: "Los Cacicazgos",
    bedrooms: 5,
    bathrooms: 4,
    area: 450,
    imageUrl: "https://picsum.photos/seed/prop4/800/450",
    type: "Casa",
    isFavorite: false,
  },
  {
    id: "5",
    title: "Apartamento Céntrico en Santiago",
    price: 28000,
    currency: "RD$",
    operation: "alquiler",
    city: "Santiago",
    sector: "Santiago Centro",
    bedrooms: 1,
    bathrooms: 1,
    area: 65,
    imageUrl: "https://picsum.photos/seed/prop5/800/450",
    type: "Apartamento",
    isFavorite: false,
  },
  {
    id: "6",
    title: "Villa Frente al Mar en La Romana",
    price: 1200000,
    currency: "USD",
    operation: "venta",
    city: "La Romana",
    sector: "La Romana",
    bedrooms: 6,
    bathrooms: 6,
    area: 800,
    imageUrl: "https://picsum.photos/seed/prop6/800/450",
    type: "Casa",
    isFavorite: true,
  },
  {
    id: "7",
    title: "Apartamento Turístico en Bávaro",
    price: 1500,
    currency: "USD",
    operation: "alquiler",
    city: "Punta Cana",
    sector: "Bávaro",
    bedrooms: 2,
    bathrooms: 2,
    area: 95,
    imageUrl: "https://picsum.photos/seed/prop7/800/450",
    type: "Apartamento",
    isFavorite: false,
  },
  {
    id: "8",
    title: "Apartamento Moderno en Serrallés",
    price: 195000,
    currency: "USD",
    operation: "venta",
    city: "Santo Domingo",
    sector: "Serrallés",
    bedrooms: 2,
    bathrooms: 2,
    area: 95,
    imageUrl: "https://picsum.photos/seed/prop8/800/450",
    type: "Apartamento",
    isFavorite: false,
  },
  {
    id: "9",
    title: "Casa Colonial en Gazcue",
    price: 12500000,
    currency: "RD$",
    operation: "venta",
    city: "Santo Domingo",
    sector: "Gazcue",
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    imageUrl: "https://picsum.photos/seed/prop9/800/450",
    type: "Casa",
    isFavorite: false,
  },
  {
    id: "10",
    title: "Terreno Privilegiado en Bávaro",
    price: 150000,
    currency: "USD",
    operation: "venta",
    city: "Punta Cana",
    sector: "Bávaro",
    bedrooms: 0,
    bathrooms: 0,
    area: 1200,
    imageUrl: "https://picsum.photos/seed/prop10/800/450",
    type: "Terreno",
    isFavorite: false,
  },
  {
    id: "11",
    title: "Edificio de Inversión en Naco",
    price: 2800000,
    currency: "USD",
    operation: "venta",
    city: "Santo Domingo",
    sector: "Naco",
    bedrooms: 12,
    bathrooms: 12,
    area: 1800,
    imageUrl: "https://picsum.photos/seed/prop11/800/450",
    type: "Edificio",
    isFavorite: false,
  },
  {
    id: "12",
    title: "Penthouse con Vista Panorámica en Piantini",
    price: 2500,
    currency: "USD",
    operation: "alquiler",
    city: "Santo Domingo",
    sector: "Piantini",
    bedrooms: 3,
    bathrooms: 2,
    area: 165,
    imageUrl: "https://picsum.photos/seed/prop12/800/450",
    type: "Apartamento",
    isFavorite: true,
  },
];
